### ISSUE TITLE
微信pushplus显示打卡成功，但github上workflow报错

### ISSUE THREAD

**Issue by zafirshi** [Long0x0/ZJU-nCov-Hitcarder-Sample#7]
您好：
我这边遇到了一些奇怪的问题：
微信推送正常，事实上也确实打卡成功，但workflow报错，报错信息如下：
```
Traceback (most recent call last):
  File "./hitcarder.py", line 243, in <module>
    ret = message.pushplus(msg, '', pushplus_token)
  File "/home/runner/work/_actions/Long0x0/zju-ncov-hitcarder/master/message.py", line 35, in pushplus
    r = requests.post(pushplus_url, data=json.dumps(data),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
```
求教一下！

**Comment by Long0x0** [comment]
已经修了
